services:

  backend:
    container_name: nestjs_observability-stack
    build: 
      context: .
    ports:
      - "3000:3000"
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9000:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    depends_on:
      - backend
  
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "5000:3000"
    volumes:
      - grafana-loki:/var/lib/grafana
    depends_on:
      - backend
  
volumes:
  prometheus_data:
  grafana-loki: