{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Service Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "{{Service Uptime}}"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"5..\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "Cpu usage %"
    }
   ]
  },
  {
   "title": "P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[1m])) * 1000",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Event loop lag (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds * 1000",
     "legendFormat": "Event Loop Lag"
    }
   ]
  },
  {
   "title": "Routes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{method}} {{route}}" }
   ]
  },
  {
   "title": "Heap Memory (Used (MB)Vs Total (MB))",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes / 1024 / 1024",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "nodejs_heap_size_total_bytes / 1024 / 1024",
     "legendFormat": "Total heap"
    }
   ]
  },
  {
   "title": "Active handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "nodejs_active_handles_total", "legendFormat": "Active Handles" }
   ]
  }
 ]
}